import os
from dotenv import load_dotenv
import google.generativeai as genai

load_dotenv()

genai.configure(api_key=os.getenv("GEMINI_API_KEY1"))

    
def aitext_reviewer(aiwritten_text):
    model = genai.GenerativeModel("models/gemini-1.5-flash")

    prompt = f"""
You are an experienced senior book editor working for a top-tier publishing house. Your job is to review a rewritten chapter generated by an AI book writer.

Please provide detailed feedback on the following aspects:

1. **Narrative Flow** – Is the story easy to follow? Are transitions between paragraphs smooth?
2. **Grammar & Sentence Structure**
3. **Tone & Style Consistency**
4. **Clarity & Readability**
5. **Suggestions for Improvement**

Do not rewrite the entire chapter. Focus only on review and feedback. Be constructive and concise.

Here is the rewritten chapter:
{aiwritten_text}
"""
    
    response = model.generate_content(prompt)
    return response.text
